// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/16/2026, 12:14:09 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/poj/innovation-awards/testing-project/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/poj/innovation-awards/testing-project/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/poj/innovation-awards/testing-project/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/poj/innovation-awards/testing-project/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/poj/innovation-awards/testing-project/app/plugins/**/*.{js,ts,mjs}","/Users/poj/innovation-awards/testing-project/app/composables/**/*.{js,ts,mjs}","/Users/poj/innovation-awards/testing-project/app/utils/**/*.{js,ts,mjs}","/Users/poj/innovation-awards/testing-project/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/poj/innovation-awards/testing-project/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/poj/innovation-awards/testing-project/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/poj/innovation-awards/testing-project/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;