// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/16/2026, 10:25:12 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/poj/antigravity/pegadaian-innovation-center/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/poj/antigravity/pegadaian-innovation-center/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/poj/antigravity/pegadaian-innovation-center/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/poj/antigravity/pegadaian-innovation-center/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/poj/antigravity/pegadaian-innovation-center/app/plugins/**/*.{js,ts,mjs}","/Users/poj/antigravity/pegadaian-innovation-center/app/composables/**/*.{js,ts,mjs}","/Users/poj/antigravity/pegadaian-innovation-center/app/utils/**/*.{js,ts,mjs}","/Users/poj/antigravity/pegadaian-innovation-center/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/poj/antigravity/pegadaian-innovation-center/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/poj/antigravity/pegadaian-innovation-center/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/poj/antigravity/pegadaian-innovation-center/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;